# Summary Assignment for Module 3
<blockquote>This is an assignment in a Jupyter notebook which will be autograded. (It is not a programming assignment but rather is using tools from a Jupyter notebook that allows for calculations and more free-form answers than the other kinds of assignments you have seen so far in this course.) To avoid autograder errors, please do not add or delete any cells. Also, run all cells even if they are hidden and not requiring any input from you. You may add additional calulations or print statements to any cell to help you see the current values of variables you may be working with. 
</blockquote>

**Rounding Error:** Ideally, your answers will be given from a direct R calculation. For example, given a matrix $A$, if you are asked to multiply the $(1,3)$ entry with the $(2,2)$ entry and to store the result in a variable `x`, you would type

<code>x = A[1,3]*A[2,2]</code>

However, if you compute `A[1,3]*A[2,2]` and see `0.23719445178`, you could choose to type out the answer as, for example,

<code>x = 0.23719445</code>

<u>as long as you keep at least 3 decimal places of accuracy</u>.

In [18]:
# Load Necesary Libraries for Autograding
library(testthat)

In [19]:
# Run this cell. It is necessary for autograding. It will also allow you to take powers of a matrix using
# "%^%" if you choose.
# Note that this cell may take a few moments to run. Do not proceed further until you see a response with a red 
# background below this cell or until "In[]" or "In[*]" to the left of the cell has a number in the brackets
library("expm")

# Problem 1

Consider a Markov chain on state space $S = \{1,2,3,4,5,6\}$ with probability transition matrix given by <br><br>

$$
\begin{array}{lcr}  &&1\,\,\,\,\,\,\,\,\,\,2\,\,\,\,\,\,\,\,\,\,3\,\,\,\,\,\,\,\,\,\,4\,\,\,\,\,\,\,\,\,\,5\,\,\,\,\,\,\,\,\,\,6\,\,\,\,\,\\
\bf{P} &=& \begin{array}{c} 1\\2\\3\\4\\5\\6\end{array}\left[ 
\begin{array}{cccccc}
0.4 & 0 & 0 & 0.5 & 0 & 0.1\\
0 & 0.8 & 0 & 0 & 0.2 & 0\\
0 & 0 & 0.3 & 0.5 & 0.2 & 0\\
0.9 & 0 & 0 & 0.1 & 0 & 0\\
0 & 0.5 & 0 & 0 & 0.5 & 0\\
0 & 0 & 0 & 1 & 0 & 0\\
\end{array}
\right]
\end{array}
$$


Run the next cell to define the matrix.

In [20]:
# Run this cell. Consider adding a "P" as the last line in the cell
# if you would like to see the matrix more clearly


P = matrix(0,6,6)
P[1,] = c(0.4,0,0,0.5,0,0.1)
P[2,] = c(0,0.8,0,0,0.2,0)
P[3,] = c(0,0,0.3,0.5,0.2,0)
P[4,] = c(0.9,0,0,0.1,0,0)
P[5,] = c(0,0.5,0,0,0.5,0)
P[6,] = c(0,0,0,1,0,0)

**Part A)** How many communication classes does this Markov chain have?

Save your answer as p1.a.

In [51]:
p1.a = NA

# your code

cat("Transition matrix P:\n")
print(P)
cat("\nRow sums (should all be 1):", rowSums(P), "\n")

n <- nrow(P)

# Step 1: Adjacency matrix (1 where P[i,j] > 0)
A <- (P > 0) * 1
cat("\nAdjacency matrix A:\n")
print(A)

# Step 2: Reachability matrix via (I + A)^(n-1) in Boolean arithmetic
# R[i,j] = 1 means state j is reachable from state i
R <- diag(n)          # start with identity (each state reaches itself)
power <- A
for (k in 1:(n - 1)) {
  R <- R + power
  power <- power %*% A
}
R <- (R > 0) * 1      # collapse to Boolean

cat("\nReachability matrix R:\n")
print(R)

# Step 3: Communication matrix — i <-> j iff both can reach each other
C <- R * t(R)
cat("\nCommunication matrix C (symmetric):\n")
print(C)

# Step 4: Extract communicating classes
visited <- rep(FALSE, n)
c_classes <- list()
for (i in 1:n) {
  if (!visited[i]) {
    members <- which(C[i, ] == 1)
    c_classes <- c(c_classes, list(members))
    visited[members] <- TRUE
  }
}

cat("\nCommunicating classes:\n")
for (k in seq_along(c_classes)) {
  cat(sprintf("  Class %d: {%s}\n", k, paste(c_classes[[k]], collapse = ", ")))
}
p1.a <- length(c_classes)

Transition matrix P:
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  0.4  0.0  0.0  0.5  0.0  0.1
[2,]  0.0  0.8  0.0  0.0  0.2  0.0
[3,]  0.0  0.0  0.3  0.5  0.2  0.0
[4,]  0.9  0.0  0.0  0.1  0.0  0.0
[5,]  0.0  0.5  0.0  0.0  0.5  0.0
[6,]  0.0  0.0  0.0  1.0  0.0  0.0

Row sums (should all be 1): 1 1 1 1 1 1

Adjacency matrix A:
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    0    0    1    0    1
[2,]    0    1    0    0    1    0
[3,]    0    0    1    1    1    0
[4,]    1    0    0    1    0    0
[5,]    0    1    0    0    1    0
[6,]    0    0    0    1    0    0

Reachability matrix R:
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    0    0    1    0    1
[2,]    0    1    0    0    1    0
[3,]    1    1    1    1    1    1
[4,]    1    0    0    1    0    1
[5,]    0    1    0    0    1    0
[6,]    1    0    0    1    0    1

Communication matrix C (symmetric):
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    0    0    1    0    1
[2,]    0    1    0    0    1    0
[3,]    0    0    1    0    0    0
[4,]    1    0    0    1    0    1
[5,]    0    1    0    0    1    0
[6,]    1    0    0    1    0    1

Communicating classes:
  Class 1: {1, 4, 6}
  Class 2: {2, 5}
  Class 3: {3}

In [52]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part B)** What are the communication classes? 

<br>
In the next cell we define a matrix called "classes". Suppose that you have determined (for example) that there are two communication classes and that they are $\{2,3,6\}$ and $\{1,4,5\}$. We will enter these classes as rows in the matrix named "classes". Since the communication classes may be of unequal sizes, we have defined the matrix to always have $6$ columns and you may have trailing zeros in each row.

For the autograder, make sure that

<ul>
<li>the elements in your classes are ordered. For example, use $\{1,4,5\}$ as opposed to $\{4,1,5\}$.</li>
<li>the rows of your matrix are ordered by the first element of your classes
</ul>

Thus, if the communication classes are $\{2,3,6\}$ and $\{1,4,5\}$, the matrix "classes" should look like

$$
\left[
\begin{array}{cccccc}
1 & 4 & 5 & 0 & 0 & 0\\
2 & 3 & 6 & 0 & 0 & 0
\end{array}
\right]
$$

In [55]:
classes = matrix(0,p1.a,6)

# your code here

for (k in seq_along(c_classes)) {
  cat(sprintf("  Class %d: {%s}\n", k, paste(c_classes[[k]], collapse = ", ")))
}


n_classes <- length(c_classes)
max_cols  <- 6

classes <- matrix(0, nrow = n_classes, ncol = max_cols)

for (i in seq_len(n_classes)) {
  members <- as.numeric(c_classes[[i]])
  classes[i, 1:length(members)] <- members
}

classes

  Class 1: {1, 4, 6}
  Class 2: {2, 5}
  Class 3: {3}

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    4    6    0    0    0
[2,] 2    5    0    0    0    0
[3,] 3    0    0    0    0    0

In [32]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part C)** Find the period for each state.

Save your answer as a vector called <code>p1.c</code> of length $6$, containing the period of states $1$, $2$, $3$, $4$, $5$, and $6$, respectively.

In [57]:
p1.c = NA
# your code here
# Period of Each State in a Markov Chain
# ---------------------------------------
# Period of state i = gcd{ n >= 1 : P^n(i,i) > 0 }
# i.e. the GCD of all return times with positive probability.
#
# For irreducible chains, all states share the same period.
# For reducible chains, states in the same communication class
# share the same period, but different classes can differ.

gcd <- function(a, b) {
  while (b != 0) {
    temp <- b
    b <- a %% b
    a <- temp
  }
  return(a)
}
 
# --- Compute period of each state ---
# Period(i) = gcd{ n >= 1 : P^n[i,i] > 0 }
# We compute P^1, P^2, ..., P^max_power and collect return times.
# For an n-state chain, the period divides n, so checking up to
# ~2*n^2 powers is more than sufficient for the GCD to stabilise.
 
max_power <- 30
Pn <- diag(n)          # P^0 = I
periods <- rep(0, n)   # will hold the period for each state
 
# Store return times for display
return_times <- vector("list", n)
for (i in 1:n) return_times[[i]] <- integer(0)
 
for (k in 1:max_power) {
  Pn <- Pn %*% P       # P^k
  for (i in 1:n) {
    if (Pn[i, i] > 1e-15) {
      return_times[[i]] <- c(return_times[[i]], k)
    }
  }
}
 
# Compute GCD of return times for each state
for (i in 1:n) {
  rt <- return_times[[i]]
  if (length(rt) == 0) {
    periods[i] <- NA     # state never returns (shouldn't happen for recurrent)
  } else if (length(rt) == 1) {
    periods[i] <- rt[1]
  } else {
    g <- rt[1]
    for (j in 2:length(rt)) {
      g <- gcd(g, rt[j])
      if (g == 1) break  # GCD=1 is minimal, no need to continue
    }
    periods[i] <- g
  }
}
 
# --- Display results ---
cat("Return times P^n[i,i] > 0 for n = 1..30:\n")
cat(strrep("-", 55), "\n")
for (i in 1:n) {
  rt <- return_times[[i]]
  # Show first few return times to keep output readable
  display <- if (length(rt) > 10) {
    paste0(paste(rt[1:10], collapse = ", "), ", ...")
  } else {
    paste(rt, collapse = ", ")
  }
  cat(sprintf("  State %d: {%s}  =>  period = %d\n", i, display, periods[i]))
}
 
# --- Verify: all states in same class must share the same period ---
# (reuse classes from previous script)
A <- (P > 0) * 1
R <- diag(n)
power <- A
for (k in 1:(n - 1)) {
  R <- R + power
  power <- power %*% A
}
R <- (R > 0) * 1
C <- R * t(R)
 
visited <- rep(FALSE, n)
classes <- list()
for (i in 1:n) {
  if (!visited[i]) {
    members <- which(C[i, ] == 1)
    classes <- c(classes, list(members))
    visited[members] <- TRUE
  }
}
 
cat("\n\nVerification — period by communicating class:\n")
cat(strrep("-", 55), "\n")
for (k in seq_along(classes)) {
  members <- classes[[k]]
  p <- unique(periods[members])
  cat(sprintf("  Class %d: {%s}  =>  period = %d\n",
              k, paste(members, collapse = ", "), p))
}

Return times P^n[i,i] > 0 for n = 1..30:
-------------------------------------------------------
  State 1: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...}  =>  period = 1
  State 2: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...}  =>  period = 1
  State 3: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...}  =>  period = 1
  State 4: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...}  =>  period = 1
  State 5: {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...}  =>  period = 1
  State 6: {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, ...}  =>  period = 1


Verification — period by communicating class:
-------------------------------------------------------
  Class 1: {1, 4, 6}  =>  period = 1
  Class 2: {2, 5}  =>  period = 1
  Class 3: {3}  =>  period = 1

In [48]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part D)** Starting from state $3$, what is the approximate probability that this Markov chain ends up in states $1$, $2$, $3$, $4$, $5$, or $6$, in the long-run?

Use the next cell to inspect high powers of the transition probability matrix until your answers are stable to three decimal places. Then move to the following cell to save your answer as a vector p1.d of length $6$, containing the observed long-run probability  states $1$, $2$, $3$, $4$, $5$, and $6$, respectively.

In [53]:
# Use this cell to take some high powers of the transition probability matrix P.
P_N = round(P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P%*%P, 3)
rownames(P_N) <- colnames(P_N) <- 1:6
P_N

  1     2     3 4     5     6
1 0.566 0.000 0 0.377 0.000 0.057
2 0.000 0.714 0 0.000 0.286 0.000
3 0.404 0.204 0 0.270 0.082 0.040
4 0.566 0.000 0 0.377 0.000 0.057
5 0.000 0.714 0 0.000 0.286 0.000
6 0.566 0.000 0 0.377 0.000 0.057

In [55]:
p1.d = NA
# your code here
p1.d = as.numeric(P_N[3,])
p1.d

[1] 0.404 0.204 0.000 0.270 0.082 0.040

In [56]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

# Problem 2

In a simplified model, the weather in a small town changes from day to day according to a Markov chain on states $1$, $2$, $3$, $4$ and $5$ where

<ul>
    <li> 1 = Sunny</li>
    <li> 2 = Cloudy</li>
    <li> 3 = Partly Cloudy</li>
    <li> 4 = Precipitation</li>
    <li> 5 = Falling kittens</li>
</ul>

Based on historical data, the transition probability matrix is <br>

$$
\begin{array}{lcr} && 1\,\,\,\,\,\,\,\,\,\,2\,\,\,\,\,\,\,\,\,\,3\,\,\,\,\,\,\,\,\,\,4\,\,\,\,\,\,\,\,\,5\,\,\,\,\,\\
\bf{P} &=& \begin{array}{c} 1\\2\\3\\4\\5\end{array}\left[ 
\begin{array}{ccccc}
0.4 & 0.2 & 0.3 & 0.1&0 \\
0.1 & 0.3 & 0.3 & 0.2 &0.1\\
0.3 & 0.3 & 0.2 & 0.2&0 \\
0.1 & 0.2 & 0.2 & 0.4&0.1\\
0.9 & 0 & 0 & 0&0.1\\
\end{array}
\right]
\end{array}
$$

Run the next cell to define the matrix.

In [57]:
# Run this cell. Consider adding a "P" as the last line in the cell
# if you would like to see the matrix more clearly
P = matrix(0,5,5)
P[1,] = c(0.4,0.2,0.3,0.1,0)
P[2,] = c(0.1,0.3,0.3,0.2,0.1)
P[3,] = c(0.3,0.3,0.2,0.2,0)
P[4,] = c(0.1,0.2,0.2,0.4,0.1)
P[5,] = c(0.9,0,0,0,0.1)

**Part A)** Is this chain irreducible? Aperiodic? Recurrent? Positive recurrent? 

Your answers should be in the form <code>TRUE</code> or <code>FALSE</code>. Capitalization matters when defining boolean variables in R. Record your answers as <code>p2.a.irreducible</code>, <code>p2.a.aperiodic</code>, <code>p2.a.recurrent</code>, and <code>p2.a.posrecurrent</code>.

In [58]:
p2.a.irreducible = TRUE
p2.a.aperiodic = TRUE
p2.a.recurrent = TRUE
p2.a.posrecurrent = TRUE
# your code here

In [59]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part B)** Find the long-run proportion of days there will be falling kittens. 

Save your answer as p2.b.
(Reminder: Give all answers to at least 3 decimal places.)

In [62]:
p2.b = NA
# your code here
A <- t(P) - diag(5)
A[5,] <- rep(1, 5)
b <- c(0, 0, 0, 0, 1)
pi_vec <- solve(A, b)
p2.b <- pi_vec[5]
p2.b

[1] 0.04914337

In [63]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part C)** Find the long-run proportion of days there will be falling kittens followed by a Sunny day. 

Save your answer as p2.c.

In [66]:
p2.c = NA
# your code here
p2.c = pi_vec[5] * P[5,1]
p2.c

[1] 0.04422904

In [65]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.

**Part D)** What is the most likely state to find this chain in in the long-run? The next most likely? The least likely?

Define a vector-valued variable <code>p2.d</code> of length $5$ that gives the corresponding rankings for states $1$ through $5$, respectively. For example, if "Sunny" is the third most likely state, the first value of p2.d should be $3$. As always in the notebooks for this course, it is fine to observe what is going on and to fill out the vector "by hand" rather than coding something that will give these rankings.

In [67]:
# This is a free cell for you to experiment in.
pi_vec

[1] 0.26780884 0.23805230 0.24075744 0.20423805 0.04914337

In [68]:
p2.d = NA
# your code here
p2.d = c(1, 3, 2, 4, 5)

In [69]:
# Hidden Test Cell
# NOTE: This cell contains hidden tests. You will not see whether you passed these tests until you submit your assignment.
# Any cell labeled "Hidden Test Cell" MAY have hidden tests.